### ISSUE TITLE
[imgur] Get image URL instead of HTML page URL

### ISSUE THREAD

**Issue by mathiasbynens** [csexton/captured-ruby#3]
After uploading an image to imgur, an URL of the following format is returned:

```
http://imgur.com/YmC0W
```

This is the URL of the imgur HTML page containing the image.

It would be great if `.png` could be automatically appended to this, and maybe also `i.` before `imgur.com`, like this:

```
http://i.imgur.com/YmC0W.png
```

This would cause the URL to be a link straight to the image instead, which is more likely to be what you want.

I don’t know Ruby, but I guess this is something that should go in [`lib/captured/uploaders/imgur_uploader.rb`](http://github.com/csexton/captured/blob/master/lib/captured/uploaders/imgur_uploader.rb), right?

**Comment by mathiasbynens** [comment]
Here’s a patch: http://github.com/mathiasbynens/captured/commit/6311d6bc66297bc6e22516b9d0e7f35ab53cb1a1

**Comment by csexton** [comment]
I originally did it this way, but seems like this undermine's imgur's business model, and the ads don't really bug me that much. I wanted to play nice.

**Comment by mathiasbynens** [comment]
If it would undermine their business model, I doubt they’d return the full image URL in their XML response.

**Comment by ghost** [comment]
I agree with mathiasbynens.

**Comment by csexton** [comment]
I understand why, but I want to do what I can for Alan and the Imgur guys, so I would like to keep that directed at the full page so he can realize some ad revinue. I would suggest using the scp option if you would prefer no ads.
