### ISSUE TITLE
Suggestion: optimize image before uploading (using pngcrunch or similar)

### ISSUE THREAD

**Issue by mathiasbynens** [csexton/captured-ruby#5]
It would be nice to have captured automatically optimize images before uploading them by running them through pngcrunch or a similar script. Maybe this could be an option in the config file?

Admittedly, it would take a little longer before the images would start uploading, but bandwidth is saved when the compressed image gets uploaded + every time someone views the image online. 

Mother nature will love you for implementing this!

**Comment by csexton** [comment]
My biggest concern about this feature is adding dependencies for an otherwise transparent feature. Seems like something that might be good if we could detect and use if present.

**Comment by mathiasbynens** [comment]
Is including it into captured not an option then? You could use a submodule for that, [like this](http://github.com/rsms/scrup/commit/4cb56f4c7131de6654f93c1fc3c3a00c93b5e515).

**Comment by csexton** [comment]
I think I am gonna keep is simple and stupid for now. This might be something worth going into Captured for Mac.
